import type { Pilot } from '@/lib/schemas';

let pilotCounter = 0;

/**
 * Creates a single mock pilot with sensible defaults.
 * All properties can be overridden.
 *
 * @param overrides - Partial pilot object to override defaults
 * @returns A complete Pilot object
 *
 * @example
 * const pilot = createMockPilot();
 * const namedPilot = createMockPilot({ name: 'Max Verstappen' });
 */
export function createMockPilot(overrides?: Partial<Pilot>): Pilot {
  pilotCounter++;
  return {
    id: `test-pilot-${pilotCounter}`,
    name: `Test Pilot ${pilotCounter}`,
    imageUrl: `https://example.com/pilot${pilotCounter}.jpg`,
    instagramHandle: undefined,
    status: 'active',
    ...overrides,
  };
}

/**
 * Creates an array of mock pilots.
 *
 * @param count - Number of pilots to create
 * @param overridesOrFactory - Either partial overrides for all pilots,
 *                             or a factory function (index) => Partial<Pilot>
 * @returns Array of Pilot objects
 *
 * @example
 * const pilots = createMockPilots(4);
 * const customPilots = createMockPilots(4, { status: 'eliminated' });
 * const indexedPilots = createMockPilots(4, (i) => ({ name: `Racer ${i}` }));
 */
export function createMockPilots(
  count: number,
  overridesOrFactory?: Partial<Pilot> | ((index: number) => Partial<Pilot>)
): Pilot[] {
  return Array.from({ length: count }, (_, index) => {
    const overrides = typeof overridesOrFactory === 'function'
      ? overridesOrFactory(index)
      : overridesOrFactory;
    return createMockPilot(overrides);
  });
}

/**
 * Resets the pilot counter.
 * Call this in beforeEach if you need predictable IDs.
 */
export function resetMockPilotCounter(): void {
  pilotCounter = 0;
}

/**
 * Creates mock pilot input (for addPilot action).
 * Does NOT include id, as that's generated by the store.
 */
export function createMockPilotInput(overrides?: Partial<Omit<Pilot, 'id'>>) {
  pilotCounter++;
  return {
    name: `Test Pilot ${pilotCounter}`,
    imageUrl: `https://example.com/pilot${pilotCounter}.jpg`,
    instagramHandle: undefined,
    ...overrides,
  };
}

/**
 * Creates mock pilot inputs for store.addPilot().
 */
export function createMockPilotInputs(count: number) {
  return Array.from({ length: count }, () => createMockPilotInput());
}
